name: Run Discord Bot

on:
  schedule:
    - cron: "*/5 * * * *"  # Запуск каждые 5 минут
  workflow_dispatch:  # Возможность ручного запуска

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Клонировать репозиторий
        uses: actions/checkout@v3

      - name: Установить Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Установить зависимости
        run: pip install -r requirements.txt

      - name: Запустить бота
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          python bot.py &
          sleep 300  # Работает 5 минут
