name: HAARROOIN  
on:  
  workflow_dispatch:  
  schedule:  
    - cron: "*/5 * * * *"  # Перезапуск каждые 5 минут  

jobs:  
  summon-bot:  
    runs-on: ubuntu-latest  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v4  

      - name: Set up Python  
        uses: actions/setup-python@v4  
        with:  
          python-version: "3.11"  

      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          pip install -r requirements.txt  

      - name: Run HAARROOIN  
        env:  
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}  
        run: |  
          nohup python bot.py &  
          sleep 300  # Удержать сессию 5 минут  
